# Generated by Django 3.1.1 on 2020-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.BigIntegerField()),
                ('artist_name', models.CharField(max_length=200)),
                ('birthplace', models.CharField(max_length=200)),
                ('art_type', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
