# Generated by Django 3.1.1 on 2020-09-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
