# Generated by Django 3.1 on 2020-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0003_auto_20200906_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='year_of_publish',
            field=models.IntegerField(),
        ),
    ]
