# Generated by Django 3.1 on 2020-09-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0004_auto_20200908_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year_of_publish',
            field=models.DateField(),
        ),
    ]
