# Generated by Django 3.1 on 2020-09-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0007_auto_20200908_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('painting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('painting_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('year_of_publish', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('painting_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_id_fk', to='art_gallery_app.artist')),
            ],
        ),
        migrations.AlterField(
            model_name='exhibition_painting',
            name='painting_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painting_id_fk', to='art_gallery_app.paintings'),
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
