# Generated by Django 3.1 on 2020-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0010_auto_20200908_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
