# Generated by Django 3.1.1 on 2020-09-09 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_gallery_app', '0011_auto_20200908_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbArtist',
            fields=[
                ('artist_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('birthplace', models.TextField()),
                ('art_type', models.TextField()),
            ],
            options={
                'db_table': 'db_artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbExhibition',
            fields=[
                ('exhibition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exhibition_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'db_exhibition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbGallery',
            fields=[
                ('gallery_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gallery_name', models.TextField()),
                ('location', models.TextField()),
            ],
            options={
                'db_table': 'db_gallery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DbPainting',
            fields=[
                ('painting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('painting_name', models.TextField()),
                ('genre', models.TextField()),
                ('year_of_publish', models.IntegerField()),
                ('price', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('painting_url', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'db_painting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='gallery_id',
        ),
        migrations.AlterUniqueTogether(
            name='exhibition_painting',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exhibition_painting',
            name='exhibition_id',
        ),
        migrations.RemoveField(
            model_name='exhibition_painting',
            name='painting_id',
        ),
        migrations.RemoveField(
            model_name='painting',
            name='artist_id',
        ),
        migrations.CreateModel(
            name='DbExhibitionPainting',
            fields=[
                ('painting', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='art_gallery_app.dbpainting')),
            ],
            options={
                'db_table': 'db_exhibition_painting',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='artist',
        ),
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='Exhibition_Painting',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
